controller_manager:
  ros__parameters:
    update_rate: 10  # Hz


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    position_controller:
      type: position_controllers/JointGroupPositionController


# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - joint1
#     interfaces:
#       - position

position_controller:
  ros__parameters:
    joints:
      - joint1

hardware:
  ros__parameters:
    hardware_interface: "arduino_hw/PWMMotorHardware"
    joints:
      - joint1
    command_interfaces:
      - joint1/position
    state_interfaces:
      - joint1/position